apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
      harness.io/track: stable
  template:
    metadata:
      labels:
        app: nginx
        harness.io/track: stable
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" #"invalid-image:latest"  # ⬅️ This will cause ImagePullError
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            timeoutSeconds: 10  # ⬅️ Liveness probe timeout set to 10 seconds
